In [2]:
import numpy as np

In [3]:
!pip install numpy

In [4]:
arr = np.array([1, 3, 4])

In [5]:
arr

array([1, 3, 4])

In [7]:
# Creating zeros array

np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# Creating ones array

np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
# Creating any values array

np.full((4,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [13]:
# Creating identity matrices 

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.arange(1, 100, 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [32]:
# Create equally spaced Array

print(np.linspace(0, 100, 5))
print(np.linspace(0, 1, 5))

print(np.linspace(1, 33, 9))
print(np.linspace(1, 33, 8))

[  0.  25.  50.  75. 100.]
[0.   0.25 0.5  0.75 1.  ]
[ 1.  5.  9. 13. 17. 21. 25. 29. 33.]
[ 1.          5.57142857 10.14285714 14.71428571 19.28571429 23.85714286
 28.42857143 33.        ]


In [43]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [44]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [45]:
print("Shape:", myarr.shape)
print("Size:", myarr.size)
print("Dimensions:", myarr.ndim) 
print("Data type:", myarr.dtype)

Shape: (4, 3)
Size: 12
Dimensions: 2
Data type: int64


In [52]:
# Changing the Data Type Explicitily


myarr3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
], dtype='float32')

In [53]:
myarr3d.ndim

3

In [54]:
myarr3d

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float32)

In [55]:
# Convert float to int

arr_int = myarr3d.astype(np.int32)

In [56]:
arr_int

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)

In [63]:
# Reshapting the Array 

reshaped = myarr.reshape((3, 4))

In [64]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [65]:
# reshaped element is same as that of previous
reshaped2 = reshaped.reshape((6, 2))

In [66]:
reshaped2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11],
       [12, 13]])

In [70]:
# Flatted Array -> Flat the entire array means make 1D fully

flatter1 = reshaped2.flatten()
print(flatter1)

flatter2 = myarr3d.flatten().astype(np.int32)
print(flatter2)

[ 1  2  3  4  5  6  7  8  9 11 12 13]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
