In [1]:
import numpy as np

In [2]:
arr = np.array([23, 4, 3, 23])

In [3]:
arr.dtype


dtype('int64')

In [4]:
# arr.astype("float32")

arr.astype(np.int32)

array([23,  4,  3, 23], dtype=int32)

In [5]:
arr2 = np.array([12, 23, 34, 45, 56], dtype="float64")

In [6]:
arr2

array([12., 23., 34., 45., 56.])

In [7]:
arr.nbytes

32

In [8]:
arr2.nbytes

40

In [9]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
print(arr_int64.nbytes)# Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)# Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [10]:
# String Data Type (Not efficient)

arr3 = np.array(['apple', 'banana', 'cherry'], dtype='U10')
print(arr)

[23  4  3 23]


In [11]:
arr3.dtype

dtype('<U10')

In [12]:
# Complex Number

arr4 = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[23  4  3 23]


In [13]:
arr4.dtype

dtype('complex128')

In [14]:
# Store Object (Not a good idea)

arr5 = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[23  4  3 23]


In [15]:
arr5

array([{'a': 1}, list([1, 2, 3]), 'hello'], dtype=object)

In [16]:
arr5.dtype

dtype('O')