In [1]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[8]

np.int64(9)

In [7]:
flat[0:3]

array([1, 2, 3])

In [8]:
flat[:5]         # Same as flat[0:5]

array([1, 2, 3, 4, 5])

In [9]:
flat[3:]         # Same as flat[3:9]

array([4, 5, 6, 7, 8, 9])

In [10]:
flat[::2]         # Every second element

array([1, 3, 5, 7, 9])

In [11]:
# Slicing returns a view, not a copy! Changes affect the original array.

slice_123 = flat[0:3]

In [12]:
slice_123

array([1, 2, 3])

In [13]:
slice_123[2] = 333

In [14]:
slice_123

array([  1,   2, 333])

In [15]:
# Numpy refer same memory location
flat


array([  1,   2, 333,   4,   5,   6,   7,   8,   9])

In [16]:
# If you want to make copy of flat use copy method
copy_arr = flat[0:3].copy()

In [17]:
copy_arr

array([  1,   2, 333])

In [18]:
copy_arr[2] = 444

In [19]:
copy_arr

array([  1,   2, 444])

In [20]:
flat

array([  1,   2, 333,   4,   5,   6,   7,   8,   9])

In [21]:
new_arr = np.array([1, 43, 54, 65, 45, 64, 23, 63])

In [22]:
# Fancy Indexing
new_arr[[3,5,7]]       # Extract 60's line Number by passing the list

array([65, 64, 63])

In [23]:
# Boolean Masking
new_arr[new_arr < 50]

array([ 1, 43, 45, 23])

In [24]:
new_arr

array([ 1, 43, 54, 65, 45, 64, 23, 63])

In [25]:
# Create a 3×3 array with random numbers
random_array = np.random.rand(3, 3) * 10 + 1

print("Array:\n", random_array)
print("Shape:", random_array.shape)

Array:
 [[9.20570768 9.6150928  3.86801793]
 [3.64514705 1.15713043 5.97563306]
 [8.34625331 1.15844783 8.15021964]]
Shape: (3, 3)


In [26]:
random_num = np.random.rand() * 10 + 1
random_num

8.422605315991484

In [27]:
float_arr = np.array([1.1, 2.2, 3.3])

In [28]:
int_arr = float_arr.astype('int32')