In [1]:
import numpy as np

In [2]:
arr = np.array([3, 5, 12, 33])

In [3]:
print(np.mean(arr))

13.25


In [4]:
print(np.min(arr))

3


In [5]:
max = np.max(arr)

In [6]:
print(max)

33


In [7]:
print(np.std(arr))

11.882234638316145


In [8]:
print(np.var(arr))

141.1875


In [9]:
print(np.sum(arr))

53


In [10]:
print(np.prod(arr))

5940


In [11]:
print(np.percentile(arr,100))  

# 1. Sort the array → x

# 2. Calculate:
#    r = (p / 100) * (n - 1)     r = 0.75 * 3  ->  (2.25)  ->  75 th according 

# 3. Split r into:
#    i = int(floor(r))     # integer part   ->   2
#    f = r - i             # fractional part      ->   0.25

# 4. Apply formula:
#    P = x[i] + f * (x[i + 1] - x[i])   ->     12 + 0.25 * (33 - 12)    ->  12 + 0.25(21)   ->  12 + 5.25

print(np.percentile(arr,75))            

33.0
17.25


In [12]:

# Rank Like System
arr2 = np.array([10, 20, 35, 40, 50])

print(np.percentile(arr2, 50))   # Median = 30
print(np.percentile(arr2, 25))   # 25th percentile = 20
print(np.percentile(arr2, 75))   # 75th percentile = 40

35.0
20.0
40.0


In [13]:
# Variance = (std^2)

# σ = sqrt( (1 / n) * Σ (xᵢ - μ)² )
# σ² = (1 / n) * Σ (xᵢ - μ)² 

print(np.std(arr2))
print(np.var(arr2))

14.2828568570857
204.0


In [14]:
a1 = [2, 3, 5, 6, 8]
a2 = [9, 13, 27, 36, 54]

np.diff(a1)
np.cumsum(a2)

array([  9,  22,  49,  85, 139])

In [15]:
# r = Σ[(x_i - x̄)(y_i - ȳ)] / (√Σ(x_i - x̄)² * √Σ(y_i - ȳ)²)

np.corrcoef(a1, a2)

array([[1.        , 0.99351307],
       [0.99351307, 1.        ]])

In [16]:
np.log(arr)

array([1.09861229, 1.60943791, 2.48490665, 3.49650756])

In [17]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 1.62754791e+05, 2.14643580e+14])

In [18]:
np.log10(100)

np.float64(2.0)

In [19]:
np.argmin(a1)

np.int64(0)

In [20]:
np.argmax(a2)

np.int64(4)

In [21]:
a3 = [ 2, 3, 3, 1, 1, 5, 5, 7, 7, 8, 2, 6, 9]

np.unique(a3)

array([1, 2, 3, 5, 6, 7, 8, 9])