In [1]:
import numpy as np
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(arr)

np.int64(45)

In [4]:
np.sum(arr, axis=0)      # Sum along rows (down each column)

array([12, 15, 18])

In [5]:
np.sum(arr, axis=1)      # Sum along columns (across each row)

array([ 6, 15, 24])

In [6]:
# Indexing in multidimensional Array is similiar in vector in math and list in python

print(arr[1][2])   # Row -> 1         Column -> 2
print(arr[2][0])   # Row -> 2         Column -> 0

6
7


In [7]:
# Numpy also give easy syntax for indexing in multidimesional array's as well as 1 D array

# For 1 D, 2 D Array 
print(arr[1,2])
print(arr[2,0])

print(arr)

# For 2 D Array (Range Indexing)
arr[0:2, 1:3]          # [included : excluded]

6
7
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [8]:
# Indexing in 3 D Array 

arr3D = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ],
        
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
# Output of arr3D.shape is → (depth, rows, columns)

print(arr3D.shape)

(2, 2, 3)


In [9]:
# Simple Indexing in 3 D Array

print(arr3D[1,1,1])
print(arr3D[0,1,2])
print()
print()


print(arr3D)
print()
print()


# Range Indexing in 3 D Array

print(arr3D[0,:,1:3])
print()
print()

print(arr3D[1,:,2])

11
6


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[2 3]
 [5 6]]


[ 9 12]


In [10]:
arr3D_1 = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6],
        [7, 8, 9]
    ],
        
    [
        [7, 8, 9],
        [10, 11, 12],
        
        [13, 14, 14]
    ],
    [
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]
    ]
])

In [11]:
arr3D_1[0:2,0:2,1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [12]:
arr3D_1[:,0,:]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [13]:
arr3D_1[:,2,2] = 0

In [14]:
arr3D_1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  0]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [13, 14,  0]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20,  0]]])